# https://golangci-lint.run/usage/configuration/

run:
  concurrency: 2
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs-use-default: true
  modules-download-mode: vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
