// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: about.proto

package handlers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type About struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Branch      string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit      string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	CommitShort string                 `protobuf:"bytes,4,opt,name=commit_short,json=commitShort,proto3" json:"commit_short,omitempty"`
	Tag         string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Dt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=dt,proto3" json:"dt,omitempty"`
}

func (x *About) Reset() {
	*x = About{}
	if protoimpl.UnsafeEnabled {
		mi := &file_about_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *About) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*About) ProtoMessage() {}

func (x *About) ProtoReflect() protoreflect.Message {
	mi := &file_about_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use About.ProtoReflect.Descriptor instead.
func (*About) Descriptor() ([]byte, []int) {
	return file_about_proto_rawDescGZIP(), []int{0}
}

func (x *About) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *About) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *About) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *About) GetCommitShort() string {
	if x != nil {
		return x.CommitShort
	}
	return ""
}

func (x *About) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *About) GetDt() *timestamppb.Timestamp {
	if x != nil {
		return x.Dt
	}
	return nil
}

var File_about_proto protoreflect.FileDescriptor

var file_about_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x75, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x2a,
	0x0a, 0x02, 0x64, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x64, 0x74, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x75, 0x6b, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x62, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x78,
	0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_about_proto_rawDescOnce sync.Once
	file_about_proto_rawDescData = file_about_proto_rawDesc
)

func file_about_proto_rawDescGZIP() []byte {
	file_about_proto_rawDescOnce.Do(func() {
		file_about_proto_rawDescData = protoimpl.X.CompressGZIP(file_about_proto_rawDescData)
	})
	return file_about_proto_rawDescData
}

var file_about_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_about_proto_goTypes = []interface{}{
	(*About)(nil),                 // 0: about.About
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_about_proto_depIdxs = []int32{
	1, // 0: about.About.dt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_about_proto_init() }
func file_about_proto_init() {
	if File_about_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_about_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*About); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_about_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_about_proto_goTypes,
		DependencyIndexes: file_about_proto_depIdxs,
		MessageInfos:      file_about_proto_msgTypes,
	}.Build()
	File_about_proto = out.File
	file_about_proto_rawDesc = nil
	file_about_proto_goTypes = nil
	file_about_proto_depIdxs = nil
}
