#!/usr/bin/env bash
#
#
# $1 cmd directory to build (e.g. ./cmd/name)
set -e

export GO111MODULE=on
export CGO_ENABLED=0
export GOFLAGS="-mod=vendor"

# Get module and default binary name from go.mod
MODULE=$(cat go.mod | grep -e "^module" | sed "s/^module //")
CMD=./cmd/${GO_MODULE##*/}

if [ $# -gt 0 ]; then
  CMD="$@"
fi

VERSION=${VERSION:-0.0.0}

VER_FLAGS=""
VER_FLAGS+=" -X '${MODULE}/build.Version=${VERSION}'"
VER_FLAGS+=" -X '${MODULE}/build.Branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)'"
VER_FLAGS+=" -X '${MODULE}/build.Commit=$(git rev-parse HEAD 2>/dev/null || true)'"
VER_FLAGS+=" -X '${MODULE}/build.CommitShort=$(git rev-parse --short HEAD 2>/dev/null || true)'"
VER_FLAGS+=" -X '${MODULE}/build.Tag=$(git describe --tags 2>/dev/null || true)'"

echo -e "Building \e[34m${CMD}\e[0m"
echo ""
set -x
${GO_EXEC:-go} build \
  -ldflags "-extldflags -static ${VER_FLAGS}" \
  "${CMD}"
