#!/usr/bin/env bash

#@go get -u golang.org/x/tools/cmd/goimports
if ! command -v goimports &> /dev/null
then
  echo "goimports does not exist"
  exit
fi

LST_CMD=${1:-"go list -mod=vendor -f '{{.Dir}}' ./..."}
CMD="goimports -l \`$LST_CMD\`"

echo ">>> goimports <<<"
echo "    ${CMD}"
FILES=$(eval $CMD)
if [[ -n "${FILES}" ]]; then
  echo "Error in files: "
  echo "${FILES}"
  echo "    Display changes: goimports -d -e \`${LST_CMD}\`"
  echo "    Fix files      : goimports -w \`${LST_CMD}\`"
  exit 1
fi

unset LST_CMD
unset CMD
unset FILES
