#!/usr/bin/env bash

#@go get -u golang.org/x/lint/golint
if ! command -v golint &> /dev/null
then
  echo "golint does not exist"
  exit
fi

LST_CMD=${1:-"go list -mod=vendor ./..."}
CMD="golint \`$LST_CMD\`"

echo ">>> golint <<<"
echo "    ${CMD}"
test -z "$(eval ${CMD} | tee /dev/stderr)" || exit 1
