#!/usr/bin/env bash
set -e

VER="${1:-4.15.2}"
DST="${2:-/usr/local/bin}"

TMP_DIRECTORY=$(mktemp -d -t "migrate_XXXXXXX")

(
cd "${TMP_DIRECTORY}"
curl --fail --silent --show-error --location "https://github.com/golang-migrate/migrate/releases/download/v${VER}/migrate.linux-amd64.tar.gz" --output "./migrate.tar.gz"
tar --extract --gzip --file="./migrate.tar.gz" -C "./"
#install ./migrate -o 0 -g 0 -m 0755 -t "${DST}"
cp ./migrate "${DST}"
)

rm -rf "${TMP_DIRECTORY}"
