// Code generated by mockery v2.46.2. DO NOT EDIT.

package internal

import mock "github.com/stretchr/testify/mock"

// MockDaemonConfigOption is an autogenerated mock type for the DaemonConfigOption type
type MockDaemonConfigOption struct {
	mock.Mock
}

type MockDaemonConfigOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDaemonConfigOption) EXPECT() *MockDaemonConfigOption_Expecter {
	return &MockDaemonConfigOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockDaemonConfigOption) Execute(_a0 *daemonConfig) {
	_m.Called(_a0)
}

// MockDaemonConfigOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDaemonConfigOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *daemonConfig
func (_e *MockDaemonConfigOption_Expecter) Execute(_a0 interface{}) *MockDaemonConfigOption_Execute_Call {
	return &MockDaemonConfigOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockDaemonConfigOption_Execute_Call) Run(run func(_a0 *daemonConfig)) *MockDaemonConfigOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*daemonConfig))
	})
	return _c
}

func (_c *MockDaemonConfigOption_Execute_Call) Return() *MockDaemonConfigOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDaemonConfigOption_Execute_Call) RunAndReturn(run func(*daemonConfig)) *MockDaemonConfigOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDaemonConfigOption creates a new instance of MockDaemonConfigOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDaemonConfigOption(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockDaemonConfigOption {
	mock := &MockDaemonConfigOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
