# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - uses: streetsidesoftware/cspell-action@v6
    #   with:
    #     root: '.'
    #     inline: warning
    #     strict: true
    #     incremental_files_only: false
    #     config: '.vscode/cspell.json'
    #     verbose: false

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: |
          .tools/
          ~/.cache/go-build/
          ~/go/pkg/
        key: ci-tools-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/go.sum', '**/Makefile', 'scripts/tools.mk', '.github/workflows/go.yml') }}
        restore-keys: |
          ci-tools-${{ runner.os }}-${{ runner.arch }}

    - name: Install Tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: make tools

    - name: env
      run: |
        make --version
        echo ''
        make env

    - name: ci-gen-n-format
      run: make ci-gen-n-format

    - name: ci-mod
      run: make ci-mod

    - name: staticcheck
      run: make staticcheck

    - name: golangci-lint
      run: make golangci-lint-github-actions

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Check shell files
      run: make ci-sh
