# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    name: Lints and Tests
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: [ '1.22', '1.23' ]
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.x"
        check-latest: true
        cache: false

    # https://github.com/actions/cache
    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: |
          .tools/
          ~/.cache/go-build/
          ~/go/pkg/
        key: ci-tools-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/go.mod', '**/go.sum', '**/Makefile', 'scripts/tools.mk', '.github/workflows/ci.yml', 'tools/tools.go') }}
        restore-keys: |
          ci-tools-${{ runner.os }}-${{ runner.arch }}

    - name: Install Tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: make tools

    - name: Env
      run: |
        make --version
        echo ""
        make env

    - name: Check Shell Files
      run: make ci-sh

    - name: Mod
      run: make ci-mod

    - name: Generate Format and Check
      run: make ci-gen-n-format

    - name: staticcheck
      run: make staticcheck

    - name: golangci-lint
      run: make golangci-lint

    - name: Test
      run: make test
