name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: |
          .ext/
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-and-tools-${{ runner.os }}-${{ hashFiles('**/go.sum', '**/Makefile') }}
        restore-keys: |
          go-and-tools-${{ runner.os }}

    - name: Install Tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: make tools

    - name: Checks
      run: make checks

    - name: Build
      run: make build

    - name: Test
      run: make test
