name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: .bin/
        key: go-tools-${{ runner.os }}-${{ hashFiles('build/ci.mk') }}
        restore-keys: |
          go-tools-${{ runner.os }}

    - name: Install Tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: make tools

    - name: Checks
      run: make checks

    - name: Build
      run: make build

    - name: Test
      run: make test
