services:
  goboilerplate:
    build:
      context: ../../
      dockerfile: ./build/docker/debug.Dockerfile
    volumes:
      - type: bind
        source: ../../
        target: /wd
      # - type: volume
      #   source: gocache
      #   target: /go/pkg/mod/cache
      #   volume:
      #     nocopy: true
    tmpfs:
      - /run
      - /tmp
    ports:
      - "8888:8888"
      - "2345:2345"
    restart: on-failure
    # https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_debug.md
    command: ["air", "-c", ".air.toml"]
    environment:
      - APP_HTTP_PORT=8888
      - APP_HTTP_INBOUND_TRAFFIC_LOG_LEVEL=2
      - APP_HTTP_OUTBOUND_TRAFFIC_LOG_LEVEL=2
      - APP_HTTP_READ_HEADER_TIMEOUT=3s
      - APP_SHUTDOWN_TIMEOUT=6s
      - APP_LOG_LEVEL=0

# volumes:
#   gocache: {}
