services:
  goboilerplate:
    build:
      context: ../../
      dockerfile: ./build/docker/Dockerfile
    environment:
      - APP_HTTP_PORT=8888
      - APP_SHUTDOWN_TIMEOUT=6s
      - APP_LOG_LEVEL=0
    ports:
      - "8888:8888"
    restart: on-failure
