services:
  goboilerplate:
    build:
      context: ../../
      dockerfile: ./build/docker/Dockerfile
    environment:
      - APP_PORT=43000
    ports:
      - "43000:43000"
    restart: on-failure
